name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build Python ${{ matrix.python }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_TEST_COMMAND: pytest {project}
          CIBW_TEST_EXTRAS: 'test'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
